const twConfig = {
  jit: true,
  corePlugins: {
    preflight: false,
  },
  prefix: "tw-",
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "hermes-blue": {
          DEFAULT: "#0091cd",
          900: "#1A9CD2",
          800: "#33A7D7",
          700: "#4DB2DC",
          600: "#66BDE1",
          500: "#80C8E6",
          400: "#99D3EB",
          300: "#B3DEF0",
          200: "#CCE9F5",
          100: "#E6F4FA",
          50: "#F2F9FC",
        },
        "hermes-blue-hover": "#006d9a",
        "hermes-blue-light": "#cce9f5",
        "hermes-orange": "#e9530e",
        "hermes-orange-hover": "#ba420c",
        "hermes-orange-light": "#ffa800",
        "hermes-signal-green": "#6ea528",
        "hermes-signal-green-light": "#d3e4be",
        "hermes-signal-yellow": "#e6aa00",
        "hermes-signal-yellow-light": "#faeecc",
        "hermes-signal-red": "#c30005",
        "hermes-signal-red-light": "#f3cccd",
        "hermes-grey": {
          DEFAULT: "#3c3c41",
          900: "#505054",
          800: "#636367",
          700: "#77777A",
          600: "#8A8A8D",
          500: "#9E9EA0",
          400: "#B1B1B3",
          300: "#C5C5C6",
          200: "#D8D8D9",
          100: "#EBEBEC",
          50: "#F5F5F5",
        },
        "hermes-grey-50": "#9d9da0",
        "hermes-grey-30": "#c4c4c6",
        "hermes-grey-10": "#ebebec",
        "hermes-grey-5": " #f5f5f6",
        "hermes-grey-light": "#e2e2e3",
      },
      fontFamily: {
        sans: [
          "Roboto",
          "Segoe\\ UI",
          "Tahoma",
          "Geneva",
          "Verdana",
          "sans-serif",
        ],
        marselis: [
          "Marselis",
          "Roboto",
          "Segoe\\ UI",
          "Tahoma",
          "Geneva",
          "Verdana",
          "sans-serif",
        ],
      },
    },
  },
  plugins: [],
}

export default twConfig
